export const GET_MAPS_REQUEST = 'GET_MAPS_REQUEST';
export const GET_MAPS_SUCCESS = 'GET_MAPS_SUCCESS';
export const GET_MAPS_ERROR = 'GET_MAPS_ERROR';
export const ADD_MAP_REQUEST = 'ADD_MAP_REQUEST';
export const ADD_MAP_SUCCESS = 'ADD_MAP_SUCCESS';
export const ADD_MAP_ERROR = 'ADD_MAP_ERROR';
